# Generated by Django 3.2.16 on 2023-05-04 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_auto_20230504_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dep_id',
            field=models.CharField(default='123', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.department')),
            ],
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='origin',
            field=models.ManyToManyField(null=True, to='scanner.Unit'),
        ),
    ]
