# Generated by Django 4.1.7 on 2023-05-06 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scanner', '0003_auto_20230504_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampledata',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='sampledata',
            name='drop_of_date',
        ),
        migrations.RemoveField(
            model_name='sampledata',
            name='reciever_id',
        ),
        migrations.RemoveField(
            model_name='sampledata',
            name='origin',
        ),
        migrations.CreateModel(
            name='DropSampleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_of_date', models.DateTimeField()),
                ('reciever_id', models.CharField(max_length=1000)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scanner.laberatory')),
                ('reviever_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sample_no', models.ManyToManyField(null=True, to='scanner.sample')),
            ],
        ),
        migrations.AddField(
            model_name='sampledata',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scanner.unit'),
        ),
    ]
