# Generated by Django 4.1.7 on 2023-05-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_remove_sampledata_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='name',
        ),
    ]
