# Generated by Django 4.1.7 on 2023-05-06 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_remove_sample_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dropsampledata',
            old_name='reviever_user',
            new_name='reciever_user',
        ),
        migrations.CreateModel(
            name='sampleshistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scanner.sampledata')),
                ('drop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scanner.dropsampledata')),
            ],
        ),
    ]
