# Generated by Django 4.1.7 on 2023-05-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_rename_reviever_user_dropsampledata_reciever_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='sampleshistory',
        ),
    ]
