# Generated by Django 4.1.7 on 2023-05-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_unit_created_date_delete_sampleshistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='created_date',
        ),
        migrations.AddField(
            model_name='sample',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
