# Generated by Django 4.1.7 on 2023-05-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_remove_unit_created_date_sample_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='collected',
            field=models.BooleanField(default=False),
        ),
    ]
