# Generated by Django 3.2.16 on 2023-05-09 13:24

from django.db import migrations, models
import scanner.models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0009_sample_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_no',
            field=models.CharField(default=scanner.models.random_string, max_length=255),
        ),
    ]
