# Generated by Django 3.2.16 on 2023-05-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0010_unit_unit_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='unit_no',
        ),
    ]
