# Generated by Django 3.2.16 on 2023-05-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0011_remove_unit_unit_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_no',
            field=models.CharField(default=9837242, max_length=255),
        ),
    ]
