# Generated by Django 4.1.7 on 2023-05-09 16:06

from django.db import migrations, models
import scanner.models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0016_alter_sampledata_sample_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='QRCode'),
        ),
        migrations.AlterField(
            model_name='department',
            name='dep_id',
            field=models.CharField(default=scanner.models.random_string, max_length=255),
        ),
    ]
