# Generated by Django 4.1.7 on 2023-05-09 16:09

from django.db import migrations, models
import scanner.models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0017_department_qr_image_alter_department_dep_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='qr_image',
        ),
        migrations.AddField(
            model_name='laberatory',
            name='lab_id',
            field=models.CharField(default=scanner.models.random_string, max_length=255),
        ),
        migrations.AddField(
            model_name='laberatory',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='QRCode'),
        ),
    ]
